DROP TABLE IF EXISTS hits;

CREATE TABLE  IF NOT EXISTS hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app       VARCHAR(32),
    uri       VARCHAR(2083),
    ip        VARCHAR(45),
    timestamp timestamp WITHOUT TIME ZONE
);